import os
import json
from datetime import datetime


class VRSceneGenerator:
    def __init__(self, output_dir="./ai_content/generated"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_scene_description(self, theme="forest"):
        templates = {
            "forest": {
                "name": "神秘森林",
                "description": "一个充满魔法的虚拟现实森林场景",
                "environment": {
                    "lighting": "柔和的阳光透过树冠",
                    "atmosphere": "宁静、神秘",
                    "time_of_day": "下午"
                },
                "objects": [
                    {"type": "tree", "count": 50, "variation": "oak, pine, birch"},
                    {"type": "rock", "count": 20, "size": "small-medium"},
                    {"type": "grass", "coverage": "80%"},
                    {"type": "flowers", "count": 30, "colors": "yellow, purple, white"}
                ],
                "interactive_elements": [
                    {"type": "teleport_pad", "positions": 5},
                    {"type": "info_panel", "content": "欢迎来到神秘森林！"}
                ]
            },
            "space": {
                "name": "太空站",
                "description": "一个未来感十足的太空站场景",
                "environment": {
                    "lighting": "星空背景 + 内部照明",
                    "atmosphere": "科幻、未来",
                    "time_of_day": "永恒"
                },
                "objects": [
                    {"type": "control_panel", "count": 10},
                    {"type": "window", "count": 5, "view": "earth"},
                    {"type": "furniture", "count": 8}
                ],
                "interactive_elements": [
                    {"type": "button", "count": 15, "function": "various"},
                    {"type": "hologram", "content": "太阳系"}
                ]
            },
            "beach": {
                "name": "热带海滩",
                "description": "一个阳光明媚的热带海滩场景",
                "environment": {
                    "lighting": "明亮的阳光",
                    "atmosphere": "放松、愉悦",
                    "time_of_day": "中午"
                },
                "objects": [
                    {"type": "palm_tree", "count": 15},
                    {"type": "beach_chair", "count": 6},
                    {"type": "umbrella", "count": 4},
                    {"type": "waves", "animation": "continuous"}
                ],
                "interactive_elements": [
                    {"type": "volleyball", "physics": "enabled"},
                    {"type": "cooler", "contents": "drinks"}
                ]
            }
        }
        return templates.get(theme, templates["forest"])

    def save_scene(self, scene_data, filename=None):
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"vr_scene_{timestamp}.json"

        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(scene_data, f, ensure_ascii=False, indent=2)

        print(f"✅ VR场景已保存: {filepath}")
        return filepath

    def generate_unity_script(self, scene_data):
        script_template = f"""
using UnityEngine;

public class AutoGeneratedScene : MonoBehaviour
{{
    void Start()
    {{
        Debug.Log("加载场景: {scene_data['name']}");
        SetupLighting();
        SpawnObjects();
    }}

    void SetupLighting()
    {{
        // {scene_data['environment']['lighting']}
    }}

    void SpawnObjects()
    {{
        // 生成游戏对象
        Debug.Log("正在生成 {len(scene_data['objects'])} 种对象");
    }}
}}
"""
        return script_template

    def save_unity_script(self, scene_data, filename=None):
        if filename is None:
            filename = f"AutoGenerated{scene_data['name']}.cs"

        filepath = os.path.join(self.output_dir, filename)
        script_content = self.generate_unity_script(scene_data)

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(script_content)

        print(f"✅ Unity脚本已保存: {filepath}")
        return filepath


if __name__ == "__main__":
    generator = VRSceneGenerator()

    themes = ["forest", "space", "beach"]
    for theme in themes:
        print(f"\n🎨 正在生成 {theme} 场景...")
        scene = generator.generate_scene_description(theme)
        generator.save_scene(scene)
        generator.save_unity_script(scene)
